### ISSUE TITLE
Long read sequencing

### ISSUE THREAD

**Issue by Acribbs** [ferrannadeu/IgCaller#2]
Hi,

Thanks for the very interesting manuscript accompanying this code. I really enjoyed reading it.

I have a question related to the functional use of the tool using long-read sequencing (nanopore). Would it be possible to use the approach you have taken to analyse Ig rearrangements using long-read cDNA/RNA sequencing?

If so, do you have any suggestions on how to modify the code accordingly. 

Thanks for your response in advance, in the meantime I will delve deeper into the code and try to work out myself. 

Adam

**Comment by Acribbs** [comment]
Its going to need a whole re-implimentation to get long read sequencing to work.

**Comment by ferrannadeu** [comment]
Hi Adam,

Thank you for your message, and sorry for the delay.

Yes, it is going to need a whole re-implementation. IgCaller aims to reconstruct the IG gene rearrangement from short reads aligned with BWA-mem in clonal/oligoclonal situations. I am not very familiar with the analysis of long reads but I guess that in this case you will have the entire IG sequence in each single read that covered the IG locus. In this case, you probably do not need to reconstruct the gene but "count" the number of reads with the same IG sequence to extract the clonality of your sample and sequence(s) of interest. The approach is remarkably different that the one used by IgCaller.

Ferran
