### ISSUE TITLE
Make igcaller installable under Anaconda

### ISSUE THREAD

**Issue by mheskett** [ferrannadeu/IgCaller#3]
Hi there
Thanks for your great work here. Would you be able to create a version that is installable under the anaconda package manager? Using package managers makes your tool usable by many more people. thanks

**Comment by ferrannadeu** [comment]
Hi @mheskett,
I am closing this issue since we are not planning to make and installable version under anaconda in the short future. Hope you can download it from here and run it without much problems. Thank you anyway for your interest!
Best,
Ferran
