### ISSUE TITLE
samtools view -F 3328 excludes split-read support for translocation

### ISSUE THREAD

**Issue by ghost** [ferrannadeu/IgCaller#4]
Hi Ferran
It looks like Ig translocations are only supported by few split reads since some would be excluded with samtools view -F 3328 (x100 and x800 flags for supplementary/secondary alignments with bwa mem ±M). It seems a bit rough to me, is there any reason to exclude split read / mate pair support from translocation scoring?
JB

**Comment by ferrannadeu** [comment]
Hi @jbalberge,

Thank you for your comment! No, there was not any reason to exclude split read/mate pair support from translocation scoring. This issue has already been fixed and will be available in the new version of the program. I will let you know once it is updated here (just doing the last checks).

Best,

Ferran

**Comment by ferrannadeu** [comment]
The updated version should solve this issue. Please, open it again if you think that it is not the case. Thanks for your input!
