### ISSUE TITLE
Mutational_signature_analysis_in_CLL

### ISSUE THREAD

**Issue by mital14** [ferrannadeu/IgCaller#9]
can't locate R script for the Mutational_signature_analysis, How to proceed for it

**Comment by ferrannadeu** [comment]
The R code to reproduce our mutational signature analysis can be found here: 

https://github.com/ferrannadeu/IgCaller/tree/master/Mutational_signature_analysis_in_CLL.

Please, note it is an R Markdown html file with both code and figures.
